[[tree_sitter_c]]
arch = "i686"
git-tree-sha1 = "f3c4c0a82e197a08ba1329030ebf628b93d57a98"
libc = "musl"
os = "linux"

    [[tree_sitter_c.download]]
    sha256 = "cadf14557c9d5fd5bf86f80329c2ae786d12df0fd73af7393b21326edaff4ac2"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+1/tree_sitter_c.v0.16.0.i686-linux-musl.tar.gz"
[[tree_sitter_c]]
arch = "aarch64"
git-tree-sha1 = "8e0e12302024ba5363d18bfdbc593e6f0d0bca62"
libc = "musl"
os = "linux"

    [[tree_sitter_c.download]]
    sha256 = "9b30d1e6c2bba9602730cde1dbf79c2a2f0b2e29883ee9d244110c424a01235f"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+1/tree_sitter_c.v0.16.0.aarch64-linux-musl.tar.gz"
[[tree_sitter_c]]
arch = "i686"
git-tree-sha1 = "0a53de301c9cc10eddd3c63207985dfdc4dda06c"
os = "windows"

    [[tree_sitter_c.download]]
    sha256 = "013390daf99e8a76596f62e1eee76e5faa7971ae6bc963ec67e499f5079c88d6"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+1/tree_sitter_c.v0.16.0.i686-w64-mingw32.tar.gz"
[[tree_sitter_c]]
arch = "x86_64"
git-tree-sha1 = "0b6c85e8cd5fefe97c28847fb9d95b330149e92c"
os = "windows"

    [[tree_sitter_c.download]]
    sha256 = "5db069659d7dadb9dd4218833aadbb3f96c6db4a78b23ed381d26f3b5b5e008e"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+1/tree_sitter_c.v0.16.0.x86_64-w64-mingw32.tar.gz"
[[tree_sitter_c]]
arch = "armv7l"
git-tree-sha1 = "647984a69cda3468a8a9a04ab319be82058c3f60"
libc = "glibc"
os = "linux"

    [[tree_sitter_c.download]]
    sha256 = "8ff1682cb320cf40fafa8fbcc834649a6db5d110c2d8240aad5e9966f888ae4c"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+1/tree_sitter_c.v0.16.0.armv7l-linux-gnueabihf.tar.gz"
[[tree_sitter_c]]
arch = "armv7l"
git-tree-sha1 = "cba5afd3ce72a1713d08458d1143c8a0761bd13d"
libc = "musl"
os = "linux"

    [[tree_sitter_c.download]]
    sha256 = "ec55c2a5b225c6efd19e007d17ff413a80fb1c12ea3cace2126fe5de77c92670"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+1/tree_sitter_c.v0.16.0.armv7l-linux-musleabihf.tar.gz"
[[tree_sitter_c]]
arch = "i686"
git-tree-sha1 = "ae8ef60c3ab3054dac63f857a628e9e05caad62f"
libc = "glibc"
os = "linux"

    [[tree_sitter_c.download]]
    sha256 = "ba9b01f2593f8c08ddd94e2ea919c4b3d7821f2afdb1040f3f29fb5a2212621c"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+1/tree_sitter_c.v0.16.0.i686-linux-gnu.tar.gz"
[[tree_sitter_c]]
arch = "x86_64"
git-tree-sha1 = "15f9df386646881430f88b4b2daf855a15a6c619"
libc = "glibc"
os = "linux"

    [[tree_sitter_c.download]]
    sha256 = "a5773c83ee8fa553d3731caacaed6beff9a76d68729e22614a6b401ac0e72459"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+1/tree_sitter_c.v0.16.0.x86_64-linux-gnu.tar.gz"
[[tree_sitter_c]]
arch = "powerpc64le"
git-tree-sha1 = "d4de4bd68ae5a7637386b5b19ad2bcf1f0fd3b89"
libc = "glibc"
os = "linux"

    [[tree_sitter_c.download]]
    sha256 = "f898c039a30998e5e88fb69a7e85294e8337c9c8c01733162663e2f8c2fc434f"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+1/tree_sitter_c.v0.16.0.powerpc64le-linux-gnu.tar.gz"
[[tree_sitter_c]]
arch = "x86_64"
git-tree-sha1 = "b7cfe91849c3042f2d91252a06393881683ecdeb"
os = "macos"

    [[tree_sitter_c.download]]
    sha256 = "9a55f31f09e30b84324ab7d30ec63596dda0180d20e71d8a2bbc4f1319b096c2"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+1/tree_sitter_c.v0.16.0.x86_64-apple-darwin14.tar.gz"
[[tree_sitter_c]]
arch = "aarch64"
git-tree-sha1 = "7f4fb3f2fe29821d6b918b923a7e044cb41a7009"
libc = "glibc"
os = "linux"

    [[tree_sitter_c.download]]
    sha256 = "7b4872e0e1d3b0cd1aa120b6d04468c13277a2a3346203898e97194e2c6b2ef1"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+1/tree_sitter_c.v0.16.0.aarch64-linux-gnu.tar.gz"
[[tree_sitter_c]]
arch = "x86_64"
git-tree-sha1 = "602f1f4f2e4c644eac670b61dd46f9ff53fb2f54"
os = "freebsd"

    [[tree_sitter_c.download]]
    sha256 = "6caaaaf4885e80443a02a448526aba82cb42b2187aaca6d356549c433a2b1587"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+1/tree_sitter_c.v0.16.0.x86_64-unknown-freebsd11.1.tar.gz"
[[tree_sitter_c]]
arch = "x86_64"
git-tree-sha1 = "ad1ee6746901a2c2070af740d31fa483921ce8cb"
libc = "musl"
os = "linux"

    [[tree_sitter_c.download]]
    sha256 = "29098bbf155446d061e53f11470842a41e5487e99441a83f36a9846b6bf236c1"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+1/tree_sitter_c.v0.16.0.x86_64-linux-musl.tar.gz"
