[[tree_sitter_c]]
arch = "aarch64"
git-tree-sha1 = "a46a5d1dad431ce84906574188f4ec082e7b6743"
libc = "musl"
os = "linux"

    [[tree_sitter_c.download]]
    sha256 = "51b39d18db026b6ae636b59abe46531ee3a857afb94e6e32b95882fe1cd5ca3e"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+0/tree_sitter_c.v0.16.0.aarch64-linux-musl.tar.gz"
[[tree_sitter_c]]
arch = "i686"
git-tree-sha1 = "4e0812b11464b4f451afd4861b9b91453fa2bdc7"
os = "windows"

    [[tree_sitter_c.download]]
    sha256 = "4169501786bc7011b66f0f390ad6590560be04110bcc291825bbed35b54bbac1"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+0/tree_sitter_c.v0.16.0.i686-w64-mingw32.tar.gz"
[[tree_sitter_c]]
arch = "x86_64"
git-tree-sha1 = "247f30b5db9b458a3d30c355111104cb5d6c1ab0"
libc = "musl"
os = "linux"

    [[tree_sitter_c.download]]
    sha256 = "5454c2d87166705f5386c295c76737695627de705f556c9aec57f703be0e34d1"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+0/tree_sitter_c.v0.16.0.x86_64-linux-musl.tar.gz"
[[tree_sitter_c]]
arch = "i686"
git-tree-sha1 = "423a6a34fffceb911cffcb7eb1974939bb4a4e84"
libc = "glibc"
os = "linux"

    [[tree_sitter_c.download]]
    sha256 = "3a13a8d4e6640e5d570dab424b80696d89460dbda7866796fa9a80581e407a92"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+0/tree_sitter_c.v0.16.0.i686-linux-gnu.tar.gz"
[[tree_sitter_c]]
arch = "armv7l"
git-tree-sha1 = "9ff6e7f8e82f6c7c14cf7de7bd50739c00e6d418"
libc = "glibc"
os = "linux"

    [[tree_sitter_c.download]]
    sha256 = "20ab18c99feee2482dbaec362108fe2f18f06fb4611a20a255fccc12b6f00eed"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+0/tree_sitter_c.v0.16.0.armv7l-linux-gnueabihf.tar.gz"
[[tree_sitter_c]]
arch = "aarch64"
git-tree-sha1 = "ca630451a098523ac40e0d5fbd714a0a9ba04e70"
libc = "glibc"
os = "linux"

    [[tree_sitter_c.download]]
    sha256 = "052114a00caf89ba42ce94309c160a93b217571d2c195c2888b6809ff656daec"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+0/tree_sitter_c.v0.16.0.aarch64-linux-gnu.tar.gz"
[[tree_sitter_c]]
arch = "x86_64"
git-tree-sha1 = "534ba664ae21ae003c0d2cb51ba4771a1c15f037"
libc = "glibc"
os = "linux"

    [[tree_sitter_c.download]]
    sha256 = "8c131df3711ad89efa2550f5db80040778acb5f6f8bddd4626895b48787317ad"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+0/tree_sitter_c.v0.16.0.x86_64-linux-gnu.tar.gz"
[[tree_sitter_c]]
arch = "powerpc64le"
git-tree-sha1 = "1cc933171893d699be6033a772c090935ef19b6b"
libc = "glibc"
os = "linux"

    [[tree_sitter_c.download]]
    sha256 = "da290fbef2b25e8c49230a0a29c6eb521f6552ceb53875bf1fbb548822e396b1"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+0/tree_sitter_c.v0.16.0.powerpc64le-linux-gnu.tar.gz"
[[tree_sitter_c]]
arch = "x86_64"
git-tree-sha1 = "6c414aa6673989964488b99aedfb76a8ddab985d"
os = "macos"

    [[tree_sitter_c.download]]
    sha256 = "3ca9a5422d2e5e9d5e0d6b4a29ae48afa48810676d4433c32478a87661167787"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+0/tree_sitter_c.v0.16.0.x86_64-apple-darwin14.tar.gz"
[[tree_sitter_c]]
arch = "x86_64"
git-tree-sha1 = "9ec85e32fc560aa6cdb4fee89ac0e3be9d94d621"
os = "freebsd"

    [[tree_sitter_c.download]]
    sha256 = "0c627bffb97bb391ed6f9ba7f562c634dd1c8b388b1552e4dba8e6ba32ce476e"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+0/tree_sitter_c.v0.16.0.x86_64-unknown-freebsd11.1.tar.gz"
[[tree_sitter_c]]
arch = "i686"
git-tree-sha1 = "b1148599b744f92d47480e2fb0e2577f7ec48be2"
libc = "musl"
os = "linux"

    [[tree_sitter_c.download]]
    sha256 = "e6cca934306d0f5ded4a13db770bee7cd6847eebf52286e9a13035cb94240947"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+0/tree_sitter_c.v0.16.0.i686-linux-musl.tar.gz"
[[tree_sitter_c]]
arch = "armv7l"
git-tree-sha1 = "f7012b7b2020a496df3467e08f9329ad8615d8f1"
libc = "musl"
os = "linux"

    [[tree_sitter_c.download]]
    sha256 = "2e60abb7493baf326e0e5722b2584ceb084d8c17e90de7f47220b0d86d8e650a"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+0/tree_sitter_c.v0.16.0.armv7l-linux-musleabihf.tar.gz"
[[tree_sitter_c]]
arch = "x86_64"
git-tree-sha1 = "6894d7fbbb3100d30c842549050585ed2153733c"
os = "windows"

    [[tree_sitter_c.download]]
    sha256 = "3f3a7ac35a1ccb22a3025938bb9a02bdbed41304cbce23ae24dc59cee412e7f0"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_c_jll.jl/releases/download/tree_sitter_c-v0.16.0+0/tree_sitter_c.v0.16.0.x86_64-w64-mingw32.tar.gz"
