# Autogenerated wrapper script for tree_sitter_c_jll for x86_64-apple-darwin14
export libtreesitter_c

## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "DYLD_FALLBACK_LIBRARY_PATH"
LIBPATH_default = "~/lib:/usr/local/lib:/lib:/usr/lib"

# Relative path to `libtreesitter_c`
const libtreesitter_c_splitpath = ["lib", "libtreesitter_c.dylib"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libtreesitter_c_path = ""

# libtreesitter_c-specific global declaration
# This will be filled out by __init__()
libtreesitter_c_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const libtreesitter_c = "@rpath/libtreesitter_c.dylib"


"""
Open all libraries
"""
function __init__()
    global artifact_dir = abspath(artifact"tree_sitter_c")

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    global libtreesitter_c_path = normpath(joinpath(artifact_dir, libtreesitter_c_splitpath...))

    # Manually `dlopen()` this right now so that future invocations
    # of `ccall` with its `SONAME` will find this path immediately.
    global libtreesitter_c_handle = dlopen(libtreesitter_c_path)
    push!(LIBPATH_list, dirname(libtreesitter_c_path))

    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ':')
    global LIBPATH = join(vcat(LIBPATH_list, [joinpath(Sys.BINDIR, Base.LIBDIR, "julia"), joinpath(Sys.BINDIR, Base.LIBDIR)]), ':')

    
end  # __init__()

